### ISSUE TITLE
Fetch API data to incorporate into app

### ISSUE THREAD

**Issue by Codo-Baggins** [Codo-Baggins/refactor_tractor_fitlit#15]

**Comment by jaypeasee** [comment]
We need to `GET` `User`, `Sleep`, `Activity`, `Hydration` data to replace the data in data files linked. See web API list below.

<img width="900" alt="Screen Shot 2020-10-28 at 1 21 34 PM" src="https://user-images.githubusercontent.com/59029768/97486032-8242dd00-1920-11eb-9e7d-caf97f916f97.png">
