### ISSUE TITLE
Activate the DOM on scripts.js

### ISSUE THREAD

**Issue by jaypeasee** [Codo-Baggins/refactor_tractor_fitlit#8]
As a user, I should be able to use this application to it's full extent by interacting with the app and clicking on specific elements on the page.

This can be accomplished by following click errors and linking the event listeners to the proper querySelectors.

**Comment by Codo-Baggins** [comment]
We have discovered that there is no ability currently to manipulate the DOM on clicks nor reason for clicks in the future. The only event listener we have is for a page load currently.
